OCAMLMAKEFILE = ../../../OCamlMakefile

SOURCES		= wtf_convert.ml
PACKS		= dbm unix
INCDIRS		= ../../../packages/ocaml-sqlite-0.3.5 ../../../libs/sqlite_util
OCAMLLDFLAGS	= sqlite.cmxa sqlite_util.cmxa
OCAMLFLAGS	=
OCAMLDEP	=
USE_CAMLP4	=
RESULT		= wtf_convert

all: nc

include $(OCAMLMAKEFILE)

