OCAMLMAKEFILE = ../../OCamlMakefile

SOURCES      = sulci_vsearch.ml
PACKS        = cgi ulex unix str
INCDIRS      = ../../libs/xml 
OCAMLLDFLAGS = xml.cmxa -linkpkg
RESULT       = sulci_vsearch.fcgi

all: nc

include $(OCAMLMAKEFILE)

