muc_log_join                   %s has become available
muc_log_leave                  %s has left
muc_log_kick                   %s has been kicked
muc_log_ban                    %s has been banned
muc_log_change_nick            %s is now known as %s
plugin_calc_not_parsed         I dont understand. 
plugin_cakc_empty_command      What?
plugin_markov_filter_badwords  Filtering out badwords
plugin_markov_kick_error       Bad moderator!
plugin_markov_phrase_is_ignore Phrase is ignored
plugin_ping_pong_from_me       For me pong from the server is %s seconds
plugin_ping_pong_from_somebody Pong from %s: %s
plugin_ping_error              n/a [%s]
plugin_ping_cannot_ping            Sorry, I cannot ping %s
plugin_ping_you_error              The information about you is secret
plugin_userinfo_error              The information is secret
plugin_userinfo_version_you        your client is %s %s - %s
plugin_userinfo_version_somebody   %s's client is %s %s - %s
plugin_userinfo_idle_me            I am not silent at all!
plugin_userinfo_idle_you           You are silent %s seconds
plugin_userinfo_idle_somebody      %s is silent %s seconds
plugin_userinfo_chat_syntax_error  "%s" is ignored
plugin_userinfo_time_me            it's %s here
plugin_userinfo_time_you           It's %s on your watch
plugin_userinfo_time_somebody      I's %s on %s's watch
plugin_roulette_suntax_error       Take a gun from father and try...
plugin_roulette_kick_reason        Pops!
plugin_roulette_bye                Adi?s!
plugin_roulette_kick_failed        Hmmm... Probably you have an immunity....
plugin_roulette_next_time          Try again....
plugin_vocabulary_invalid_suntax   hm?
plugin_vocabulary_wrote            wrote.
plugin_vocabulary_not_found        dunno