error_server_feature_not_implemented   The server %s does not implement this feature
error_client_feature_not_implemented   %s's client does not implement this feature
error_remote_server_timeout    The server %s is not available
error_remote_server_not_found  Does the server %s exist?

error_server_service_unavailable      Currently this service at %s is unavailable
error_your_service_unavailable      Currently your service is unavailable
error_client_service_unavailable    Currently %s's service is unavailable
error_recipient_unavailable         %s is temporaly unavailable 
error_not_allowed                 Nobody allows me to ask %s
error_any_error                   Failed to ask %s.

invalid_entity                 What? Whom?

muc_log_join                   %s has become available
muc_log_leave                  %s has left
muc_log_leave_reason           %s has left: %s
muc_log_kick                   %s has been kicked
muc_log_kick_reason            %s has been kicked: %s
muc_log_ban                    %s has been banned
muc_log_ban_reason             %s has been banned: %s
muc_log_change_nick            %s is now known as %s
muc_log_set_subject            %s has set the subject to: %s
muc_log_subject                Theme: %s

plugin_calc_not_parsed         I dont understand. 
plugin_calc_empty_command      What?
plugin_calc_divide_by_zero     Please dont divide by zero!
plugin_calc_number_too_big         Too big number... :(
plugin_calc_cannot_float_fact      No, I don't know how to calculate float factorial :(
plugin_calc_negative_number        Impossible..

plugin_markov_kick_reason      Filtering out badwords
plugin_markov_kick_error       Bad moderator!
plugin_markov_phrase_is_ignored Phrase is ignored

plugin_ping_pong_from_me       For me pong from the server is %s
plugin_ping_pong_from_you      Pong from you: %s
plugin_ping_pong_from_somebody Pong from %s: %s

plugin_userinfo_status_whose       Whose status?
plugin_userinfo_idle_me            I am not silent at all!
plugin_userinfo_idle_you           You are silent %s
plugin_userinfo_idle_somebody      %s is silent %s
plugin_userinfo_uptime             %s's uptime is %s
plugin_userinfo_version_you        your client is %s %s - %s
plugin_userinfo_version_somebody   %s's client is %s %s - %s
plugin_userinfo_version_server     %s is running %s %s (%s)
plugin_userinfo_time_me            it's %s here
plugin_userinfo_time_you           It's %s on your watch
plugin_userinfo_time_somebody      It's %s on %s's watch
plugin_userinfo_time_server        at %s there is %s

plugin_roulette_syntax_error       Take a gun from father and try...
plugin_roulette_kick_reason        Pops!
plugin_roulette_bye                Adi?s!
plugin_roulette_kick_failed        Hmmm... Probably you have an immunity....
plugin_roulette_next_time          Try again....
plugin_roulette_not_allowed        Sorry, I dont have rights.

plugin_vocabulary_invalid_syntax   hm?
plugin_vocabulary_recorded         wrote
plugin_vocabulary_dfn_again        it already was done
plugin_vocabulary_removed          removed
plugin_vocabulary_nothing_to_remove nothing to remove
plugin_vocabulary_replaced         replaced
plugin_vocabulary_answer           %s said that %s - %s
plugin_vocabulary_db_is_empty      data base is empty
plugin_vocabulary_not_found        dunno
plugin_vocabulary_records          %s records

plugin_misc_dns_invalid_syntax     what dns?
plugin_misc_dns_not_resolved       cannot resolve

plugin_google_invalid_syntax       hm?
plugin_google_not_found            Not found :(
plugin_google_adv_invalid_syntax   He-he! You have not guessed the proper syntax
plugin_google_no_answer            [no answer]
plugin_google_server_error         Google is broken
plugin_google_server_404           Probably Google is broken

plugin_google_translate_not_parsed Cannot parse the response from Google
plugin_google_translate_server_error Google Translator is broken
plugin_google_translate_bad_syntax   Sorry, but I don't understand.

plugin_weather_invalid_syntax      Hmm... whose weather?
plugin_weather_server_error        Weather Service is broken.
plugin_weather_404                 No such airport.
plugin_weather_not_parsed          Cannot parse the response from NOAA server

plugin_admin_quit_bye              Bye! I'm gone...
plugin_admin_quit_no_access        Who should to quit?
plugin_admin_join_no_access        Sorry, I dont want to go to there.
plugin_dict_invalid_syntax         Invalid syntax, my dear.
plugin_dict_db_not_found           No such db
plugin_dict_word_not_found         Cannot found anything suitable

plugin_seen_whom                  Whom?
plugin_seen_is_here               Peer here, %s is sitting here.
plugin_seen_changed_nick          %s is known as  %s
plugin_seen_is_not_same           %s is here right now, but he is not the same %s which is known for me
plugin_seen_you                   Looking for a mirror...
plugin_seen_left                  %s has left %sago
plugin_seen_kicked                %s has been kicked %sago
plugin_seen_banned                %s has been banned %sago
plugin_seen_left_reason           %s has left %sago: %s
plugin_seen_kicked_reason         %s has been kicked %sago: %s
plugin_seen_banned_reason         %s has been banned %sago: %s
plugin_seen_never_seen            I did not see %s here.
plugin_seen_not_in_room           This command is available only in conferences
plugin_seen_greet_updated         Updated
plugin_seen_greet_added           Added
plugin_seen_greet_bad_syntax      Bad syntax

plugin_talkers_top_header_man     Man
plugin_talkers_top_header_words   Words
plugin_talkers_top_header_actions Actions
plugin_talkers_top_header_sentences Phrs.
plugin_talkers_top_header_average   Avg.
plugin_talkers_no_result            No such guys

plugin_translate_not_parsed       Cannot understand what the translator said.
plugin_translate_server_error     The translator is broken.
plugin_translate_bad_language     Unknown language, try another one.
plugin_translate_bad_syntax       Hmm?

plugin_yandex_server_error        Yandex is broken.
plugin_yandex_404                 Yandex cannot execute the query.
plugin_yandex_bad_syntax          What?
plugin_yandex_not_found           not found

plugin_currency_no_currency       No such currency %s
plugin_currency_too_big_number    it's impossible to have so much money

plugin_hostip_bad_syntax          Please give an address.
plugin_hostip_failed              Failed to make a request

plugin_cerberus_cannot_kick_admin what do you say?