muc_log_ban_reason             %s ha sido bloqueado: %s
muc_log_ban                    %s ha sido bloqueado
muc_log_change_nick            %s ha cambiado el nombre a %s
muc_log_join                   %s ha conectado
muc_log_kick_reason            %s ha sido expulsado: %s
muc_log_kick                   %s ha sido expulsado
muc_log_leave_reason           %s se ha ido: %s
muc_log_leave                  %s se ha ido
//muc_log_set_subject
//muc_log_subject
plugin_admin_join_no_access    Lo siento, pero no quiero ir ahí.
plugin_admin_quit_bye          Me voy, ¡Hasta luego!
plugin_admin_quit_no_access    ¿Quién quiere salir?
plugin_calc_cannot_float_fact      No, no se como calcular factoriales flotantes
plugin_calc_empty_command      ¿Qué?
plugin_calc_negative_number        Imposible.
plugin_calc_not_parsed         No lo entiendo. 
plugin_calc_number_too_big         Número demasiado grande
plugin_calc_divide_by_zero     división por cero
plugin_dict_db_not_found       No existe esa Base de Datos
plugin_dict_invalid_syntax     Sintaxis incorrecta.
plugin_dict_word_not_found     Palabra no encontrada

plugin_globalstats_stats_error     Parece que el servidor no proporciona estadísticas
plugin_globalstats_uptime_error    La información es secreta
plugin_globalstats_uptime_invalid_syntax ¡Te falta el nombre del servidor, pequeño saltamontes!
//plugin_globalstats_uptime_not_implemented This server does not know how long it works
//plugin_globalstats_uptime_remote_server_not_found This server is not an jabber-server
plugin_globalstats_uptime      %s lleva activo %s
plugin_google_adv_invalid_syntax   Je je, no has adivinado la sintaxis correcta

plugin_google_invalid_syntax       ¿eh?
plugin_google_not_found            No encontrado :(
plugin_markov_filter_badwords  Filtrando palabras malas
plugin_markov_kick_error       ¡Mal moderador!
plugin_markov_kick_reason          Razón de la expulsión
plugin_markov_phrase_is_ignored    Se ignora la frase
plugin_misc_dns_invalid_syntax     ¿Qué DNS?
plugin_misc_dns_not_resolved       no se pudo resolver
plugin_ping_cannot_ping            Lo siento, no puedo hacer ping a %s
plugin_ping_error              n/a [%s]
plugin_ping_pong_from_me       Pong de mi al servidor:  %s
plugin_ping_pong_from_somebody Pong de %s: %s
plugin_ping_pong_from_you      Pong de ti: %s
plugin_ping_you_error              La información sobre ti es desconocida
plugin_roulette_bye                ¡Sayonara, baby!
plugin_roulette_kick_failed        Hmmm... Probablemente tengas inmunidad...
plugin_roulette_kick_reason        ¡Pops!
plugin_roulette_next_time          Prueba otra vez...
plugin_roulette_suntax_error       Coge un arma del padre y prueba...
plugin_seen_banned_reason         %s fue bloqueado hace %s: %s: %s
plugin_seen_banned                %s fue bloqueado hace %s
plugin_seen_changed_nick          %s ha cambiado el nombre a %s
plugin_seen_is_here               %s está aquí.
plugin_seen_is_not_same           %s está ahora aquí, pero no es el mismo %s que yo conocía
plugin_seen_kicked_reason         %s fue expulsado hace %s: %s
plugin_seen_kicked                %s fue expulsado hace %s
plugin_seen_left_reason           %s se fue hace %s: %s
plugin_seen_left                  %s se fue hace %s
plugin_seen_never_seen            Nunca he visto a ese tal %s
plugin_seen_not_in_room           Este comando solo está disponible en salas de charla
plugin_seen_you                   Buscando un espejo...
plugin_userinfo_chat_syntax_error  "%s" se ignora
plugin_userinfo_error              La información es secreta
plugin_userinfo_idle_me            ¡Yo no estoy ausente!
plugin_userinfo_idle_somebody      %s está ausente desde hace %s
plugin_userinfo_idle_you           Estás ausente desde hacer %s
plugin_userinfo_time_me            son las %s aqui
plugin_userinfo_time_somebody      Son las %s en el reloj de %s
plugin_userinfo_time_you           Son las %s en tu reloj
plugin_userinfo_version_somebody   el cliente de %s es %s %s - %s
//plugin_userinfo_version_server     %s is running %s
plugin_userinfo_version_you        tu cliente es %s %s - %s
plugin_vocabulary_invalid_suntax   ¿eh?
plugin_vocabulary_not_found        no lo se
plugin_vocabulary_wrote            escrito.
plugin_weather_invalid_syntax     Esto... ¿el tiempo de dónde?
//plugin_talkers_top_header_man     Man
//plugin_talkers_top_header_words   Words
//plugin_talkers_top_header_actions Actions
//plugin_talkers_top_header_sentences Sentences
//plugin_talkers_top_header_average   Avg.
//plugin_talkers_no_result            No such guys