muc_log_join                   %s betrad de kamer
muc_log_leave                  %s verliet de kamer
muc_log_leave_reason           %s verliet de kamer: %s
muc_log_kick                   %s werd gekicked
muc_log_kick_reason            %s werd gekicked: %s
muc_log_ban                    %s werd verbannen
muc_log_ban_reason             %s werd verbannen: %s
muc_log_change_nick            %s is nu gekend onder de naam %s
//muc_log_set_subject
//muc_log_subject
plugin_calc_not_parsed         Ik versta dat niet. 
plugin_calc_empty_command      Wat?
plugin_calc_divide_by_zero         Делим на нолик, да? :-/
plugin_calc_number_too_big         Een te groot getal... :(
plugin_calc_cannot_float_fact      Nee, ik weet echt niet hoe ik de faculteit van een kommagetal zou kunnen berekenen :(
plugin_calc_negative_number        Onmogelijk..
plugin_markov_filter_badwords  Woorden uit de zwarte lijst werden weggefilterd
plugin_markov_kick_error       Slechte moderator!
plugin_markov_phrase_is_ignore De zin werd genegeerd
plugin_ping_pong_from_me       Mijn pong van de server is %s seconden
plugin_ping_pong_from_you      Jouw pong: %s seconden
plugin_ping_pong_from_somebody %s's pong: %s
plugin_ping_error              n/a [%s]
plugin_ping_cannot_ping            Sorry, ik kan %s niet pingen
plugin_ping_you_error              Jouw gegevens zijn geheim
plugin_userinfo_error              Deze gegevens zijn geheim
plugin_userinfo_version_you        uw client is %s %s - %s
plugin_userinfo_version_somebody   %s's client is %s %s - %s
//plugin_userinfo_version_server     %s is running %s
plugin_userinfo_idle_me            Ik ben helemaal niet stil!
plugin_userinfo_idle_you           Je bent al %s seconden stil
plugin_userinfo_idle_somebody      %s is al %s seconden stil
plugin_userinfo_chat_syntax_error  "%s" werd genegeerd
plugin_userinfo_time_me            Hier is het %s
plugin_userinfo_time_you           Bij u is het %s
plugin_userinfo_time_somebody      Bij %s is het %s
plugin_roulette_syntax_error       Neem een pistool en haal de trekker over...
plugin_roulette_kick_reason        Pang!
plugin_roulette_bye                Tot weerziens!
plugin_roulette_kick_failed        Hmmm... Jij lijkt onsterfelijk te zijn...
plugin_roulette_next_time          Probeer opnieuw....
plugin_vocabulary_invalid_syntax   hm?
plugin_vocabulary_wrote            geschreven.
plugin_vocabulary_not_found        Ik zou het niet weten
plugin_misc_dns_invalid_syntax     welke dns?
plugin_misc_dns_not_resolved       kan niet opzoeken
plugin_globalstats_uptime_invalid_syntax Je moet de servernaam opgeven!
plugin_globalstats_uptime_error    De gegevens zijn geheim
plugin_globalstats_stats_error     Die server ondersteunt geen statistieken
//plugin_globalstats_uptime_not_implemented This server does not know how long it works
//plugin_globalstats_uptime_remote_server_not_found This server is not an jabber-server
//plugin_globalstats_stats_error     No support for stats
plugin_google_invalid_syntax       hm?
plugin_google_not_found            Niet gevonden :(
plugin_google_adv_invalid_syntax   Haha! Je hebt de juiste syntaxis niet kunnen gokken
plugin_weather_invalid_syntax      Hmm... wat zei je juist?
plugin_admin_quit_bye              Tot nog eens! Ik ben er eens mee weg...
plugin_admin_quit_no_access        Wie zou weg moeten?
plugin_admin_join_no_access        Sorry, ik wil zover niet gaan.
plugin_dict_invalid_syntax         Onjuiste syntaxis, mijn beste.
plugin_dict_db_not_found           Database werd niet gevonden
plugin_dict_word_not_found         Kan niets bruikbaars vinden
//plugin_seen_is_here               Peer here, %s is sitting here.
//plugin_seen_changed_nick          %s is known as  %s
//plugin_seen_is_not_same           %s is here right now, but he is not the same %s which is known for me
//plugin_seen_you                   Looking for a mirror...
//plugin_seen_left                  %s has left %sago
//plugin_seen_kicked                %s has been kicked %sago
//plugin_seen_banned                %s has been banned %sago
//plugin_seen_left_reason           %s has left %sago: %s
//plugin_seen_kicked_reason         %s has been kicked %sago: %s
//plugin_seen_banned_reason         %s has been banned %sago: %s
//plugin_seen_never_seen            I did not see %s here.
//plugin_seen_not_in_room           This command is available only in conferences
//plugin_talkers_top_header_man     Man
//plugin_talkers_top_header_words   Words
//plugin_talkers_top_header_actions Actions
//plugin_talkers_top_header_sentences Sentences
//plugin_talkers_top_header_average   Avg.
//plugin_talkers_no_result            No such guys