muc_log_join                       %s появился в конференции
muc_log_leave                      %s удалился из конференции
muc_log_kick                       %s кикнули из конференции
muc_log_ban                        %s забанён
muc_log_change_nick                %s переименовался в %s
plugin_calc_not_parsed             что это было?!
plugin_calc_empty_command          ась?
plugin_markov_kick_reason          фильтруем базар
plugin_markov_kick_error           Фиговый модератор!
plugin_markov_phrase_is_ignored    Фраза игнорируется
plugin_ping_pong_from_me           Скорость отклика сервера для меня составляет %s секунд
plugin_ping_pong_from_you          Понг от тебя %s
plugin_ping_pong_from_somebody     Понг от %s: %s
plugin_ping_error                  Информация у %s засекречена
plugin_ping_cannot_ping            Не могу пинговать %s
plugin_ping_you_error              Информация о тебе засекречена
plugin_userinfo_error              Информация засекречена
plugin_userinfo_version_you        у тебя клиент %s %s - %s
plugin_userinfo_version_somebody   у %s клиент %s %s - %s
plugin_userinfo_idle_me            я вообще не молчу!
plugin_userinfo_idle_you           Молчишь %s
plugin_userinfo_idle_somebody      %s молчит %s
plugin_userinfo_chat_syntax_error  "%s" игнорируется
plugin_userinfo_time_me            Щас у меня в %s
plugin_userinfo_time_you           У тебя в компе показываются %s
plugin_userinfo_time_somebody      У %s в компе показываются %s
plugin_roulette_suntax_error       Возьми у отца ружье и попробуй...
plugin_roulette_kick_reason        Пшиииик!
plugin_roulette_bye                Адью.
plugin_roulette_kick_failed        Ыыыы... у тебя наверное иммунитет....
plugin_roulette_next_time          Как-нить в следующий раз...
