muc_log_join                       %s вошел(а) в комнату
muc_log_leave                      %s вышел(а) из комнаты
muc_log_leave_reason               %s вышел(а) из комнаты: %s
muc_log_kick                       %s выгнали из комнаты
muc_log_kick_reason                %s выгнали из комнаты: %s
muc_log_ban                        %s запретили входить в комнату
muc_log_ban_reason                 %s запретили входить в комнату: %s
muc_log_change_nick                %s изменил(а) имя на %s
muc_log_set_subject                %s изменил(а) тему: %s
muc_log_subject                    Тема: %s
plugin_calc_not_parsed             что это было?!
plugin_calc_empty_command          ась?
plugin_calc_divide_by_zero         Делим на нолик, да? :-/
plugin_calc_number_too_big         Многовато... :(
plugin_calc_cannot_float_fact Не, я не умею вычислять факториал нецелых чисел :(
plugin_calc_negative_number        Так не бывает.
plugin_markov_kick_reason          фильтруем базар
plugin_markov_kick_error           Фиговый модератор!
plugin_markov_phrase_is_ignored    Эта фраза игнорируется
plugin_ping_pong_from_me           Скорость отклика сервера для меня составляет %s
plugin_ping_pong_from_you          Понг от тебя %s
plugin_ping_pong_from_somebody     Понг от %s: %s
plugin_ping_error                  Информация у %s засекречена
plugin_ping_cannot_ping            Не могу пинговать %s
plugin_ping_you_error              Информация о тебе засекречена
plugin_userinfo_error              Информация засекречена
plugin_userinfo_version_you        у тебя клиент %s %s - %s
plugin_userinfo_version_somebody   у %s клиент %s %s - %s
plugin_userinfo_version_server     на %s запущен %s %s (%s)
plugin_userinfo_version_server_not_implemented  Сервер %s ничего не знает о себе
plugin_userinfo_version_server_remote_server_timeout Сервер %s отвалился по таймауту
plugin_userinfo_version_server_remote_server_not_found Скорее всего,чы на %s не поднят джаббер сервер
plugin_userinfo_version_server_error Информация засекречена
plugin_userinfo_idle_me            я вообще не молчу!
plugin_userinfo_idle_you           Молчишь %s
plugin_userinfo_idle_somebody      %s молчит %s
plugin_userinfo_chat_syntax_error  "%s" игнорируется
plugin_userinfo_time_me            Щас у меня в компе %s
plugin_userinfo_time_you           У тебя в компе показываются %s
plugin_userinfo_time_somebody      У %s в компе показываются %s
plugin_roulette_syntax_error       Возьми у отца ружье и попробуй...
plugin_roulette_kick_reason        Пшиииик!
plugin_roulette_bye                Адью.
plugin_roulette_kick_failed        Ыыыы... у тебя наверное иммунитет....
plugin_roulette_next_time          Как-нить в следующий раз...
plugin_vocabulary_invalid_syntax   ну?
plugin_vocabulary_wrote            записал.
plugin_vocabulary_not_found        хз
plugin_misc_dns_invalid_syntax     ась?
plugin_misc_dns_not_resolved       не резолвится

plugin_globalstats_uptime          Сервер %s работает без остановок %s
plugin_globalstats_uptime_invalid_syntax Имя сервера, сестричка!
plugin_globalstats_uptime_error    Информация засекречена
plugin_globalstats_uptime_not_implemented Сервер не считает свой аптайм
plugin_globalstats_uptime_remote_server_not_found Скорее всего там не поднят джаббер-сервер
plugin_globalstats_stats_error     Скорее всего, сервер не поддерживает stats
plugin_google_invalid_syntax       ась?
plugin_google_not_found            Не нашел :(
plugin_google_adv_invalid_syntax   гы! Не угадал синтаксис.
plugin_weather_invalid_syntax     гы! попробуй еще разок, сына!
plugin_admin_quit_bye             Пока! Я ушел...
plugin_admin_quit_no_access       Это ты мне? Quit? Фиг!
plugin_admin_join_no_access       Не, с тобой я не пойду туда.
plugin_dict_invalid_syntax        гы! Инвалид синтаксис.
plugin_dict_db_not_found          Нет такой базы данных
plugin_dict_word_not_found        Не найдено ничего подходящего
plugin_seen_is_here               Вглядись в комнату. %s здесь сидит.
plugin_seen_changed_nick          %s скрывается под ником %s
plugin_seen_is_not_same           %s сидит здесь, но это не тот самый %s, который мне известен.
plugin_seen_you                   Посмотри на себя в зеркало!
plugin_seen_left                  %s был здесь %sназад
plugin_seen_kicked                %s был выпровожен отсюда %sназад
plugin_seen_banned                %s был забанён %sназад: %s
plugin_seen_left_reason           %s был здесь %sназад: %s
plugin_seen_kicked_reason         %s был выпровожен отсюда %sназад: %s
plugin_seen_banned_reason         %s был забанён %sназад: %s: %s
plugin_seen_never_seen            Я никогда здесь не видел %s.
plugin_seen_not_in_room           Эта команда доступна только в конференциях
plugin_talkers_top_header_man     Болтун
plugin_talkers_top_header_words   Слов
plugin_talkers_top_header_actions /me
plugin_talkers_top_header_sentences Фраз
plugin_talkers_top_header_average   Эфф.
plugin_talkers_no_result          Нет таких болтунов.
