error_server_feature_not_implemented   Сервер %s не поддерживает эту фичу
error_client_feature_not_implemented   У %s'клиент не поддерживает эту фичу
error_remote_server_timeout    Сервер %s отвалился по таймауту
error_remote_server_not_found  %s не существует!
error_server_service_unavailable   Запрошенный сервис у %s сдох.
error_your_service_unavailable   Запрошенный у вас сервис отключен.
error_client_service_unavailable   Запрошенный сервис у %s отключен.
error_recipient_unavailable        %s временно недоступен
error_not_allowed                  Никто не разрешил запрашивать информацию у %s
error_any_error                    Не удалось запросить информацию у %s.

invalid_entity                     А? Кого?

muc_log_join                       %s вошел(а) в комнату
muc_log_leave                      %s вышел(а) из комнаты
muc_log_leave_reason               %s вышел(а) из комнаты: %s
muc_log_kick                       %s выгнали из комнаты
muc_log_kick_reason                %s выгнали из комнаты: %s
muc_log_ban                        %s запретили входить в комнату
muc_log_ban_reason                 %s запретили входить в комнату: %s
muc_log_unmember                   %s лишили членства и изгнали из комнаты
muc_log_unmember_reason            %s лишили членства и изгнали из комнаты: %s
muc_log_change_nick                %s изменил(а) имя на %s
muc_log_set_subject                %s изменил(а) тему: %s
muc_log_subject                    Тема: %s

plugin_calc_not_parsed             что это было?!
plugin_calc_empty_command          ась?
plugin_calc_divide_by_zero         Делим на нолик, да? :-/
plugin_calc_number_too_big         Многовато... :(
plugin_calc_cannot_float_fact Не, я не умею вычислять факториал нецелых чисел :(
plugin_calc_negative_number        Так не бывает.

plugin_markov_kick_reason          фильтруем базар
plugin_markov_kick_error           Фиговый модератор!
plugin_markov_phrase_is_ignored    Эта фраза игнорируется

plugin_ping_pong_from_me           Скорость отклика сервера для меня составляет %s
plugin_ping_pong_from_you          Понг от тебя %s
plugin_ping_pong_from_somebody     Понг от %s: %s

plugin_userinfo_status_whose       Чей статус?
plugin_userinfo_idle_me            я вообще не молчу!
plugin_userinfo_idle_you           Молчишь %s
plugin_userinfo_idle_somebody      %s молчит %s
plugin_userinfo_uptime             %s работает без остановок %s
plugin_userinfo_version_you        у тебя клиент %s %s - %s
plugin_userinfo_version_somebody   у %s клиент %s %s - %s
plugin_userinfo_version_server     на %s запущен %s %s (%s)
plugin_userinfo_time_me            Щас у меня в компе %s
plugin_userinfo_time_you           У тебя в компе показываются %s
plugin_userinfo_time_somebody      У %s в компе показываются %s
plugin_userinfo_time_server        на %s щас %s

plugin_roulette_syntax_error       Возьми у отца ружье и попробуй...
plugin_roulette_kick_reason        Пшиииик!
plugin_roulette_bye                Адью.
plugin_roulette_kick_failed        Ыыыы... у тебя наверное иммунитет....
plugin_roulette_next_time          Как-нить в следующий раз...
plugin_roulette_not_allowed        Прав не имею.
plugin_vocabulary_invalid_syntax   ну?
plugin_vocabulary_recorded         записал.
plugin_vocabulary_dfn_again        это уже было
plugin_vocabulary_removed          стёр
plugin_vocabulary_nothing_to_remove а был ли мальчик?
plugin_vocabulary_replaced         переписал
plugin_vocabulary_answer           %s сказал(а), что %s - %s
plugin_vocabulary_db_is_empty      база знаний пуста
plugin_vocabulary_not_found        хз
plugin_vocabulary_records          %s записей

plugin_misc_dns_invalid_syntax     ась?
plugin_misc_dns_not_resolved       не резолвится

plugin_google_invalid_syntax       ась?
plugin_google_not_found            Не нашел :(
plugin_google_adv_invalid_syntax   гы! Не угадал синтаксис.
plugin_google_no_answer            [нет ответа]
plugin_google_server_error         Гугль сломался.
plugin_google_server_404           Хмм.. что-то с урлом. Гугль выдает 404.

plugin_google_translate_not_parsed Не смог распарсить ответ от  Google
plugin_google_translate_server_error Переводчик Гугла сломался.
plugin_google_translate_bad_syntax   Не понял!

plugin_weather_invalid_syntax     гы! попробуй еще разок, сына!
plugin_weather_server_error       Погода сломалась :(
plugin_weather_404                Нет такого аэропорта.
plugin_weather_not_parsed         Не получилось распарсить ответ на запрос о погоде

plugin_admin_quit_bye             Пока! Я ушел...
plugin_admin_quit_no_access       Это ты мне? Quit? Фиг!
plugin_admin_join_no_access       Не, с тобой я не пойду туда.

plugin_dict_invalid_syntax        гы! Инвалид синтаксис.
plugin_dict_db_not_found          Нет такой базы данных
plugin_dict_word_not_found        Не найдено ничего подходящего

plugin_seen_whom                  Кого?
plugin_seen_is_here               Вглядись в комнату. %s здесь сидит.
plugin_seen_changed_nick          %s скрывается под ником %s
plugin_seen_is_not_same           %s сидит здесь, но это не тот самый %s, который мне известен.
plugin_seen_you                   Посмотри на себя в зеркало!
plugin_seen_left                  %s был здесь %sназад
plugin_seen_kicked                %s был выпровожен отсюда %sназад
plugin_seen_banned                %s был забанен %sназад
plugin_seen_unmembered            %s был лишен членства и изгран из комнаты %sназад
plugin_seen_left_reason           %s был здесь %sназад: %s
plugin_seen_kicked_reason         %s был выпровожен отсюда %sназад: %s
plugin_seen_banned_reason         %s был забанен %sназад: %s: %s
plugin_seen_unmembered_reason     %s был лишен членства и изгран из комнаты %sназад: %s
plugin_seen_never_seen            Я никогда здесь не видел %s.
plugin_seen_not_in_room           Эта команда доступна только в конференциях
plugin_seen_greet_updated         Обновил
plugin_seen_greet_added           Добавил
plugin_seen_greet_bad_syntax      Неправильный синтаксис команды

plugin_talkers_top_header_man     Болтун
plugin_talkers_top_header_words   Слов
plugin_talkers_top_header_actions /me
plugin_talkers_top_header_sentences Фраз
plugin_talkers_top_header_average   Эфф.
plugin_talkers_no_result          Нет таких болтунов.

plugin_translate_not_parsed       Не могу понять ответ переводчика!
plugin_translate_server_error     Переводчик сломался.
plugin_translate_bad_language     Я не знаю такого языка, попробуй другой?
plugin_translate_bad_syntax       Хммм?

plugin_yandex_server_error        Яндекс сломался.
plugin_yandex_404                 Яндексу не нравится такой запрос...
plugin_yandex_bad_syntax          Чего?
plugin_yandex_not_found           Не нашёл. :(

plugin_currency_no_currency       Нет такой валюты %s
plugin_currency_too_big_number    Так не бывает!

plugin_hostip_bad_syntax          Какой адрес?
plugin_hostip_failed              Не удалось сделать запрос.

plugin_cerberus_cannot_kick_admin не болтай глупостей как малолетка!